spring:
  application:
    name: cpumonitor

  datasource:
    # mariaDB
    url: jdbc:mariadb://localhost:3307/cpu_monitor?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 1000