spring:
  application:
    name: cpumonitor

  datasource:
    # H2 DB
    url: jdbc:h2:tcp://localhost/~/cpumonitor
    driverClassName: org.h2.Driver
    username: sa
    password: cpumonitor

    # mariaDB
    #url: jdbc:mariadb://localhost:3306/cpu_monitor
    #username:
    #password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
