spring:
  application:
    name: cpumonitor

  profiles:
    include: file:.env

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
